name: Local Sync Only

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 * * * *'  # 每小时自动执行

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: {}  # 不需要任何权限，因为不推送

    steps:
      - name: Checkout without token
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史

      - name: Configure git
        run: |
          git config --global user.name "Auto Sync"
          git config --global user.email "auto-sync@users.noreply.github.com"

      - name: Backup protected files
        run: |
          mkdir -p .sync_backup
          [ -d .github/workflows/ ] && cp -R .github/workflows/ .sync_backup/
          [ -f README.md ] && cp README.md .sync_backup/

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Fansirsqi/Sesame-TK.git || true
          git fetch upstream main

      - name: Reset local files
        run: |
          git checkout -B main upstream/main --force
          git reset --hard upstream/main

      - name: Restore protected files
        run: |
          [ -d .sync_backup/workflows ] && {
            rm -rf .github/workflows
            mv .sync_backup/workflows .github/
          }
          [ -f .sync_backup/README.md ] && mv .sync_backup/README.md ./
          rm -rf .sync_backup

      - name: Show local changes
        run: |
          echo "=== 本地已更新 ==="
          echo "保留的文件："
          ls -la .github/workflows/ README.md
          echo "其他文件已同步上游版本"
          git status
