name: Selective Sync with rsync

on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          path: 'target'
          token: ${{ secrets.PAT }}

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/Fansirsqi/Sesame-TK.git
          git fetch upstream

      - name: Prepare upstream files
        run: |
          mkdir -p upstream
          git --work-tree=upstream checkout upstream/main -- .

      - name: Debug directory structure
        run: |
          echo "=== Directory Structure ==="
          echo "Upstream content:"
          ls -l upstream/
          echo "Target content:"
          ls -l target/

      - name: Run rsync with exclusions
        run: |
          rsync -av --delete \
            --exclude='.git/' \
            --exclude='.github/workflows/' \  # 保留原有工作流
            --exclude='/README.md' \          # 排除根目录README.md
            --exclude='.syncignore' \         # 可选：排除同步规则文件
            upstream/ target/

      - name: Verify sync results
        run: |
          echo "=== Post-Sync Verification ==="
          echo "Checking preserved files:"
          ls -l target/.github/workflows/
          cat target/README.md || echo "README.md preserved"

      - name: Commit and push changes
        run: |
          cd target
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore: sync excluding workflows and README" || echo "No changes"
          git push
