name: Selective Fork Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 每小时自动同步

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          path: 'Sesame-TK'
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Fetch upstream changes
        run: |
          cd local_repo
          git remote add upstream https://github.com/Fansirsqi/Sesame-TK.git || true
          git fetch upstream main

      - name: Backup excluded files
        run: |
          cd local_repo
          mkdir -p .sync_backup
          cp -a .github/workflows/ .sync_backup/
          cp README.md .sync_backup/ || echo "README.md not found"

      - name: Hard reset to upstream
        run: |
          cd local_repo
          git checkout --force upstream/main
          git reset --hard upstream/main

      - name: Restore excluded files
        run: |
          cd local_repo
          rm -rf .github/workflows/
          mv .sync_backup/workflows/ .github/ || echo "No workflows to restore"
          mv .sync_backup/README.md ./ || echo "No README to restore"
          rm -rf .sync_backup

      - name: Commit selective changes
        run: |
          cd local_repo
          git config user.name "GitHub Actions"
          git config user.email "216294726+myblsky66@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: sync excluding workflows and README"
          git push origin main
