name: Robust Rsync Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target
        uses: actions/checkout@v4
        with:
          path: 'target_repo'
          token: ${{ secrets.PAT }}

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/Fansirsqi/Sesame-TK.git
          git fetch upstream

      - name: Prepare upstream
        run: |
          mkdir -p upstream_repo
          git --work-tree=upstream_repo checkout upstream/main -- .

      - name: Validate paths
        run: |
          echo "=== Path Verification ==="
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Upstream path: $(pwd)/upstream_repo"
          echo "Target path: $(pwd)/target_repo"
          ls -ld $GITHUB_WORKSPACE upstream_repo target_repo

      - name: Run rsync (debug)
        run: |
          cd $GITHUB_WORKSPACE
          rsync -avn \  # Dry-run first
            --exclude='.git/' \
            --exclude='.github/workflows/' \
            --exclude='/README.md' \
            upstream_repo/ target_repo/

      - name: Execute rsync
        run: |
          cd $GITHUB_WORKSPACE
          rsync -av --delete \
            --exclude='.git/' \
            --exclude='.github/workflows/' \
            --exclude='/README.md' \
            upstream_repo/ target_repo/

      - name: Commit changes
        run: |
          cd target_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: sync excluding workflows and README"
          git push
