name: Selective Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 每小时自动同步

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Backup protected files
        run: |
          backup_dir=".sync_backup_$(date +%s)"
          mkdir -p "$backup_dir"
          [ -d .github/workflows/ ] && cp -a .github/workflows/ "$backup_dir"/
          [ -f README.md ] && cp README.md "$backup_dir"/
          echo "BACKUP_DIR=$backup_dir" >> $GITHUB_ENV

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/Fansirsqi/Sesame-TK.git || true
          git fetch upstream main

      - name: Reset to upstream
        run: |
          git checkout -B main upstream/main --force

      - name: Restore protected files
        run: |
          [ -d "$BACKUP_DIR/workflows" ] && {
            rm -rf .github/workflows/
            mv "$BACKUP_DIR/workflows" .github/
          }
          [ -f "$BACKUP_DIR/README.md" ] && mv "$BACKUP_DIR/README.md" ./
          rm -rf "$BACKUP_DIR"

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "216294726+myblsky66@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "没有需要保留的更改"
          else
            git commit -m "chore: 保留本地workflows和README"
            git push origin main
          fi
