name: Fixed Rsync Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target
        uses: actions/checkout@v4
        with:
          path: 'local_repo'  # 修改为更明确的目录名
          token: ${{ secrets.PAT }}

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/Fansirsqi/Sesame-TK.git
          git fetch upstream

      - name: Prepare upstream
        run: |
          mkdir -p upstream_src && cd upstream_src
          git init
          git remote add origin https://github.com/Fansirsqi/Sesame-TK.git
          git fetch origin main
          git checkout origin/main -f

      - name: Validate directory structure
        run: |
          echo "=== Directory Structure ==="
          echo "Upstream:"
          ls -la upstream_src/
          echo "Local:"
          ls -la local_repo/
          echo "Working dir: $(pwd)"

      - name: Run fixed rsync
        run: |
          # 使用绝对路径确保准确性
          rsync -av --delete \
            --exclude='.git/' \
            --exclude='.github/workflows/' \
            --exclude='/README.md' \
            "$(pwd)/upstream_src/" "$(pwd)/local_repo/"  # 关键修复：使用绝对路径

          # 验证同步结果
          echo "=== Sync Verification ==="
          ls -la local_repo/.github/workflows/
          [ -f local_repo/README.md ] && echo "README.md preserved"

      - name: Commit changes
        run: |
          cd local_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: sync with exclusions"
          git push
